language: perl
perl:
  - "5.14"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libapache2-mod-perl2 libdbd-mysql-perl libtimedate-perl libnet-dns-perl libnet-ldap-perl libio-socket-ssl-perl libpdf-api2-perl libdbd-mysql-perl libsoap-lite-perl libgd-text-perl libtext-csv-xs-perl libjson-xs-perl libgd-graph-perl libapache-dbi-perl libxml-libxml-perl libxml-xslt-perl

script: bin/otrs.Console.pl Dev::UnitTest::Run

