language: perl
perl:
  - "5.14"

services:
  - mysql
  - postgresql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdbd-mysql-perl libtimedate-perl libnet-dns-perl libnet-ldap-perl libio-socket-ssl-perl libpdf-api2-perl libdbd-mysql-perl libsoap-lite-perl libtext-csv-xs-perl libjson-xs-perl libapache-dbi-perl libxml-libxml-perl libxml-libxslt-perl libyaml-perl libarchive-zip-perl libcrypt-eksblowfish-perl libencode-hanextra-perl libmail-imapclient-perl libtemplate-perl

install:
  - cpanm --quiet --notest Code::TidyAll Perl::Tidy Perl::Critic Plack
  - scripts/tools/travis/setup.sh
  - sudo plackup --port 80 bin/cgi-bin/app.psgi

script:
  - bin/otrs.CheckModules.pl
  - bin/otrs.Console.pl Maint::Database::Check
  - bin/otrs.Console.pl Maint::Config::Rebuild
  - bin/otrs.Console.pl Dev::UnitTest::Run

